NFC_ROOT=$(srctree)/techpack/nfc-st

LINUXINCLUDE   += -I$(NFC_ROOT)/../../techpack/securemsm/smcinvoke/
LINUXINCLUDE   += -I$(NFC_ROOT)/../../techpack/securemsm/linux/

obj-m += stm_nfc_i2c.o

ccflags-y := $(call cc-option,-Wno-misleading-indentation)
stm_nfc_i2c-y :=  nfc/st21nfc.o
